apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-repo
spec:
  storageClassName: artifact-fs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  parameters:
    remoteURL: "https://github.com/torvalds/linux.git"
    branch: "master"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-artifact-fs
spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: repo
          mountPath: /mnt/repo
          readOnly: true
  volumes:
    - name: repo
      persistentVolumeClaim:
        claimName: example-repo
